### ISSUE TITLE
Needs new initial proposal

### ISSUE THREAD

**Issue by jal5313** [sarahbethfederman/PathMan#1]
We need a new proposal to show Decause... Preferably with more info than the last one.

**Comment by IAmRasputin** [comment]
This can be closed.

**Comment by jal5313** [comment]
It's not pushed to the repo yet. Soon.

**Comment by IAmRasputin** [comment]
Wait, really?  Well, it's written and I posted it to my blog.  Whoops.

**Comment by jal5313** [comment]
Closed for good. Proposal is up.
