### ISSUE TITLE
isValid function

### ISSUE THREAD

**Issue by sarahbethfederman** [sarahbethfederman/PathMan#4]
We need a function in the pattern class that can take an array of moves that's as long as the pattern, and returns true if the last move move was a valid move for the pattern

This will be called from the Game class.

**Comment by IAmRasputin** [comment]
I propose that this be a function in the game class, which takes the desired direction, the grid, and the player as input.

**Comment by jal5313** [comment]
IAmRasputin, is this good to close?

**Comment by IAmRasputin** [comment]
Yep.  I think we have a pretty good version of this now.
